# Generated by Django 4.1.4 on 2022-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_title",
                    models.CharField(max_length=100, verbose_name="Project Title"),
                ),
                (
                    "project_description",
                    models.TextField(verbose_name="Project Description"),
                ),
                (
                    "project_technology",
                    models.CharField(max_length=20, verbose_name="Technology Used"),
                ),
                (
                    "project_image",
                    models.FilePathField(path="/img", verbose_name="Project Image"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
